name: Deploy Script
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: SerheyJankowsky/ssh-action@v1
        with:
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_user: ${{ secrets.SSH_USER }}
          # ssh-port: ${{ secrets.SSH_PORT }}
          ssh_password: ${{ secrets.SSH_PASSWORD }}
          env_vars: "MY_SECRET,APP_ENV=production,DB_HOST=localhost"
          script: |
            echo "Secret: $MY_SECRET"
            echo "Environment: $APP_ENV"
            echo "Database: $DB_HOST"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
